[WIP] Add FFmpeg-cuda Support
marqo-ai/marqo pull request #1030
Opened 2024-11-01 03:46 UTC by wanliAlex

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
we only allow CPU to do ffmpeg video decoding

* **What is the new behavior (if this is a feature change)?**
we try to use GPU to do ffmpeg decoding when possible

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
running

* **Related Python client changes** (link commit/PR here)
no

* **Related documentation changes** (link commit/PR here)
no

* **Other information**:
no

* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes/features)
- [X] Docs have been added / updated (for bug fixes / features)

2024-11-25 00:00 UTC, papa99do requested changes

2024-11-25 00:00 UTC, papa99do commented on src/marqo/tensor_search/on_start_script.py
> +        result = subprocess.run(ffmpeg_command_gpu_check, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Consider handle timeout and other exceptions. Something like this:
```
try:
    result = subprocess.run(
        ffmpeg_command_gpu_check,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,          # Raises CalledProcessError for non-zero exit codes
        text=True,           # Decodes bytes to strings using default encoding
        timeout=30           # Optional: Set a timeout in seconds
    )
except subprocess.CalledProcessError as e:
    raise exceptions.StartupSanityCheckError(
                f"Failed to use GPU acceleration for video processing. "
                f"Ensure that your system has the required dependencies installed. "
                f"You can set 'MARQO_ENABLE_VIDEO_GPU_ACCELERATION=FALSE' to disable GPU acceleration. "
                f"Check {marqo_docs.configuring_marqo()} for more information. "
                f"Original error message: {result.stderr}"
            ) from e
except subprocess.TimeoutExpired as e:
     raise exceptions.StartupSanityCheckError(.....) from e
except Exception as e:
     raise exceptions.StartupSanityCheckError(.....) from e
```

2024-11-25 00:00 UTC, papa99do commented on src/marqo/tensor_search/streaming_media_processor.py
> +                    chunk_end = min([chunk_start + chunk_duration, self.duration])
Why do we put them in a list?

2024-11-25 00:00 UTC, papa99do commented on src/marqo/tensor_search/streaming_media_processor.py
> +        result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
When calling subprocess.run, we should carefully handle the possible exceptions to avoid failing the whole batch for a failure in one chunk or file. Please refer to https://docs.python.org/3/library/subprocess.html#exceptions for more details about what errors could be thrown. 
Also, subprocess.run is blocking, should we consider introduce timeout (and optional retry?) when downloading video/audio chunks? I'm not sure what could be a good default, but we should not block indefinitely.

2024-11-25 00:00 UTC, papa99do commented on src/marqo/tensor_search/streaming_media_processor.py
> +            )
I think a better approach is always inject `enable_video_gpu_acceleration` value in the constructor. This will allow us to unit test this class with out mocking `read_env_vars_and_defaults`.  `download_and_chunk_media` in `add_docs.py` seems to be only function that constructs this class. It's a top-level function, we can call `utils.read_env_vars_and_defaults` there.

2024-11-25 10:09 UTC, wanliAlex commented on src/marqo/tensor_search/streaming_media_processor.py
> +                    chunk_end = min([chunk_start + chunk_duration, self.duration])
The IDE will raised a type warning before the change so I fixed it. The behaviour is exactly the same.

2024-11-25 10:13 UTC, wanliAlex commented on src/marqo/tensor_search/streaming_media_processor.py
> +            )
done. I move the method to add_docs.py

2024-11-25 10:45 UTC, wanliAlex commented on src/marqo/tensor_search/on_start_script.py
> +        result = subprocess.run(ffmpeg_command_gpu_check, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Resolved. I try to avoid catching general exceptions here.

2024-11-25 11:00 UTC, wanliAlex commented on src/marqo/tensor_search/streaming_media_processor.py
> +        result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
I added more error catches. I propose adding a retry in a different PR.

2024-11-26 03:46 UTC, papa99do commented on src/marqo/tensor_search/streaming_media_processor.py
> +
Why do we pick these values specifically to calculate the timeout?

2024-11-27 01:11 UTC, papa99do approved these changes, later dismissed
LGTM

2024-11-27 01:16 UTC, papa99do approved these changes, later dismissed

2024-11-27 21:41 UTC, papa99do approved these changes
LGTM

2024-11-27 22:26 UTC, merged