Restructure tests
marqo-ai/marqo pull request #1047
Opened 2024-11-21 02:56 UTC by farshidz

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2024-12-24 02:23 UTC, papa99do commented
Hello @farshidz , I noticed you moved all the exisiting unit and integ tests to the integ_tests folder. What is the plan to distinguish integ tests from unit tests going forward?

2024-12-24 04:44 UTC, farshidz commented
> Hello @farshidz , I noticed you moved all the exisiting unit and integ tests to the integ_tests folder. What is the plan to distinguish integ tests from unit tests going forward?

Unit tests will be in `unit_tests`

2025-01-08 07:07 UTC, wanliAlex requested changes

2025-01-08 07:07 UTC, wanliAlex commented on .github/workflows/arm64_docker_marqo.yml
> +          Otherwise, the specified Docker image is tested. For example "marqoai/marqo:test"
Does the image need to be public? Can we test an image on ECR? You can assign a role to the EC2 instance to grant the pull access from ECR: https://github.com/machulav/ec2-github-runner?tab=readme-ov-file#inputs

2025-01-08 07:07 UTC, wanliAlex commented on .github/workflows/cpu_local_marqo.yml
> +          bash scripts/start_local_marqo.sh $MARQO_IMAGE_NAME
When we start local marqo, we need to start a stand-alone vespa container. Should we start a specific Vespa version that is identical to the version inside Marqo container?

2025-01-13 06:53 UTC, farshidz commented on .github/workflows/cpu_local_marqo.yml
> +          bash scripts/start_local_marqo.sh $MARQO_IMAGE_NAME
Vespa version is hard-coded in `start_vespa.py` and we should update this as we update the Vespa in marqo base. Did you have something different in mind?

2025-01-13 06:53 UTC, farshidz commented on .github/workflows/arm64_docker_marqo.yml
> +          Otherwise, the specified Docker image is tested. For example "marqoai/marqo:test"
ECR a follow-up task as discussed

2025-01-13 08:46 UTC, wanliAlex commented on .github/workflows/cpu_local_marqo.yml
> +          bash scripts/start_local_marqo.sh $MARQO_IMAGE_NAME
You can set the environment variable to control the version: https://github.com/marqo-ai/marqo/pull/1047/files#diff-9bbc399ad2fc5c88e6d8528dbb42b4410fbc5b9136eea6faf3da4137feb3d1dcR24

I am thinking we should set this env variable so all tests are using the same Vespa version.

2025-01-28 05:08 UTC, wanliAlex submitted a review, later dismissed
LGTM

2025-02-03 22:54 UTC, wanliAlex approved these changes

2025-02-03 23:09 UTC, merged