Multinode-HA Vespa Setup for Local Testing
marqo-ai/marqo pull request #1071
Opened 2024-12-16 17:33 UTC by vicilliar

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Testing improvement

* **What is the current behavior?** (You can also link to an open issue here)
Current vespa setup only uses a single node. 

* **What is the new behavior (if this is a feature change)?**
We implement a multinode setup for local vespa, so we can simulate cloud shards and replicas.
`vespa_local.py start` function now accepts `--Shards` and `--Replicas` as parameters. If Shards > 1 or Replicas > 0, multinode vespa setup is used. Multinode vespa setup has 3 config server nodes, max(2, total_content_nodes / 4) API nodes, and shards * (1 + replicas) content nodes.
Unit test github workflow now accepts shards and replicas as parameters.
Orchestrator workflow was created, which runs 4 unit tests setups:
(1) 0 replicas, 1 shard
(2) 1 replica, 1 shard
(3) 0 replicas, 2 shards
(4) 1 replica, 2 shards

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
In progress

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2025-01-02 23:18 UTC, papa99do commented on .github/workflows/unit_test_200gb_CI.yml
> +              echo "MULTINODE_TEST_ARGS=--multinode --ignore=tests/core/index_management/test_index_management.py --ignore=tests/core/inference --ignore=tests/processing --ignore=tests/s2_inference"
We should exclude all the unit tests that do not use Vespa to save some time (some long running tests do not use vespa at all). Let's create a ticket to track this improvement.

2025-01-02 23:25 UTC, papa99do commented on .github/workflows/unit_test_200gb_CI.yml
> +
We can consolidate this by querying the convergence status from CONFIG_URL in an interval. If the the cluster is convergent after deploying the vespa app package, then all nodes must be up and running.

2025-01-02 23:26 UTC, papa99do commented on .github/workflows/unit_test_200gb_CI.yml
> +          pytest ${{ env.MULTINODE_TEST_ARGS }} --ignore=tests/test_documentation.py --ignore=tests/backwards_compatibility_tests --durations=100 --cov=src --cov-branch --cov-context=test --cov-repor
This is outdated, please merge the mainline change first.

2025-01-02 23:27 UTC, papa99do commented on .github/workflows/unit_tests_with_shards_and_replicas.yml
> +  Unit-Tests-1-Shard-0-Replica:
Is this a duplicate run?

2025-01-02 23:41 UTC, papa99do commented on .github/workflows/unit_test_200gb_CI.yml
> +          zip -r vespa_tester_app.zip . -x README.md .env .gitignore "*.yml"  # zip the whole directory except for the listed files
If we don't want to keep the zip file, we can pipe the output of zip to curl command. In this case, we don't need to clean up the files or even copy files around. Example:
`zip -r - . -x README.md .env .gitignore "*.yml" |  curl --header Content-Type:application/zip --data-binary @- http://localhost:19071/application/v2/tenant/default/prepareandactivate`

2025-01-02 23:43 UTC, papa99do commented on scripts/vespa_local/vespa_local.py
> +import docker
We will need these deps in `requirements.dev.txt` file

2025-01-02 23:48 UTC, papa99do commented on scripts/vespa_local/vespa_local.py
> +class VespaLocalMultiNode:
The logic in this class is worth testing (to make sure the generated docker compose file and config files are as expected). Can we write a test for this class?

2025-01-03 04:17 UTC, vicilliar commented on .github/workflows/unit_test_200gb_CI.yml
> +              echo "MULTINODE_TEST_ARGS=--multinode --ignore=tests/core/index_management/test_index_management.py --ignore=tests/core/inference --ignore=tests/processing --ignore=tests/s2_inference"
I agree, although our test suite now is quite confusing, and many tests that don't use vespa are interwoven with ones that do, with no concrete structure to differentiate them. We should have these tests manually tagged. It also adds overhead for future tests made, to always be marked with either `@pytest.mark.uses_vespa` or `@pytest.mark.no_vespa`

2025-01-03 04:25 UTC, vicilliar commented on .github/workflows/unit_tests_with_shards_and_replicas.yml
> +  Unit-Tests-1-Shard-0-Replica:
This is the same as a normal unit test run, good point. If we intend to keep running standard unit tests I'll remove this

2025-01-20 10:24 UTC, vicilliar commented on .github/workflows/unit_test_200gb_CI.yml
> +              echo "MULTINODE_TEST_ARGS=--multinode --ignore=tests/core/index_management/test_index_management.py --ignore=tests/core/inference --ignore=tests/processing --ignore=tests/s2_inference"
Ticket created: https://s2search.atlassian.net/jira/polaris/projects/MOSD/ideas/view/4863474?selectedIssue=MOSD-318&issueViewLayout=sidebar&issueViewSection=overview&atlOrigin=eyJpIjoiM2ZkNjRkYTUzZjljNGZhOGE3MmNmMDdmYzJhYzcwOTEiLCJwIjoiaiJ9

2025-01-20 10:26 UTC, vicilliar commented on .github/workflows/unit_test_200gb_CI.yml
> +          pytest ${{ env.MULTINODE_TEST_ARGS }} --ignore=tests/test_documentation.py --ignore=tests/backwards_compatibility_tests --durations=100 --cov=src --cov-branch --cov-context=test --cov-repor
done

2025-01-20 10:37 UTC, vicilliar commented on .github/workflows/unit_test_200gb_CI.yml
> +          zip -r vespa_tester_app.zip . -x README.md .env .gitignore "*.yml"  # zip the whole directory except for the listed files
done

2025-01-20 11:31 UTC, vicilliar commented on scripts/vespa_local/vespa_local.py
> +import docker
yaml is already a requirement here in marqo-base: https://github.com/marqo-ai/marqo-base/blob/main/requirements/amd64-gpu-requirements.txt#L323

2025-01-20 11:59 UTC, vicilliar commented on scripts/vespa_local/vespa_local.py
> +import docker
docker is already a dependency of one of our reqs in requirements.dev.txt, but I'll add both docker and PyYaml with pinned versions to requirements.dev.txt just in case

2025-01-22 08:59 UTC, vicilliar commented on scripts/vespa_local/vespa_local.py
> +class VespaLocalMultiNode:
done

2025-01-22 09:00 UTC, vicilliar commented on .github/workflows/unit_test_200gb_CI.yml
> +
done

2025-01-30 00:45 UTC, papa99do submitted a review, later dismissed
Look great. Thanks for adding the unit test to make sure the compose file and configs are generated correctly.

2025-01-30 09:47 UTC, papa99do approved these changes

2025-01-30 22:59 UTC, papa99do requested changes

2025-01-30 22:59 UTC, papa99do commented on .github/workflows/unit_test_200gb_CI.yml
> +  Determine-Vespa-Setup:
This step should be run after `Check-Changes`, and should be run only if check-changes returns true:
`if: ${{ needs.Check-Changes.outputs.doc_only == 'false' }} # Run only if there are non-documentation changes`

2025-01-30 22:59 UTC, papa99do commented on .github/workflows/unit_test_200gb_CI.yml
> +          pytest ${{ env.MULTINODE_TEST_ARGS }} --ignore=tests/test_documentation.py --ignore=tests/compatibility_tests \
It seems MULTINODE_TEST_ARGS is not passed in correctly (or maybe is not populated correctly in the first place?)

2025-02-03 04:24 UTC, vicilliar commented on .github/workflows/unit_test_200gb_CI.yml
> +          pytest ${{ env.MULTINODE_TEST_ARGS }} --ignore=tests/test_documentation.py --ignore=tests/compatibility_tests \
It is passed in correctly for multinode runs. Please check this 2 shard 1 replica run: https://github.com/marqo-ai/marqo/actions/runs/13106217962/job/36561470973#step:9:15

MULTINODE_TEST_ARGS will be empty string for 1 shard and 0 replicas. Maybe that's the one you saw.

2025-02-23 22:14 UTC, papa99do approved these changes, later dismissed

2025-02-24 11:15 UTC, wanliAlex approved these changes

2025-02-24 11:26 UTC, papa99do approved these changes

2025-02-25 02:05 UTC, merged