Custom Languagebind Model Loading
marqo-ai/marqo pull request #1072
Opened 2024-12-17 03:13 UTC by wanliAlex

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature and bug fix

* **What is the current behavior?** (You can also link to an open issue here)
We do not support custom languagebind model loading

* **What is the new behavior (if this is a feature change)?**
This PR includes several changes:
- Support for custom Languagebind models loading from a zip file via url, a zip file via s3, and a hf repo
- Fix a bug where Languagebind models do not preprocess the image right after downloading
- Fix a bug where Languagebind model can't take more than 1 video or 1 audio in the weighted search query

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
running

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2025-01-07 03:33 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +    MODEL_NAME_CLIP_TYPE_MAPPING = {
We can also move these to model properties. But will it be a breaking change?

2025-01-07 05:34 UTC, farshidz requested changes

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +    MODEL_NAME_CLIP_TYPE_MAPPING = {
Not sure what you mean. As in having the user specify these?

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +class CLIPType(MarqoBaseModel):
The name doesn't seem appropriate. Why is this called CLIPType?

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +            raise InvalidModelPropertiesError(
There's also a `cause` argument in `MarqoError` though I'm not sure how useful it is -- it's not currently used anywhere

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                    f"If you are loading a custom model, please provide the modelLocation and remove the 'name' field "
Trailing whitespace

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                if modality == Modality.TEXT or modality == Modality.TEXT_2:
What's TEXT_2?

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +            raise InternalError("Invalid model properties provided. Either 'name' or 'modelLocation' must be provided.")
Is this not a user input error? Why InternalError?

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        """Custom tokenizer loading. The tokenizer can be loaded in twa ways:
two ways

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        elif tokenizer_location.hf and (not tokenizer_location.hf.filename):
What if there is a filename?

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                elif model_location.hf and not model_location.hf.filename:
What if there is a file name? The `else` clause doesn't seem to work for this

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        if isinstance(content[0], str):
Is the assumption that all items in the list are of the same type? Also note `content` could be an empty list leading to an error when you try to access index 0

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +        """Validate that at least one location is provided."""
Shouldn't it be exactly one?

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +        """Validate that at least one location is provided."""
Seems to be what the code does too

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +        auth_required = values.get("authRequired")
I believe we established that `authRequired` is currently a no-op and we intend to remove it. We should probably keep it that way and not consider its value

2025-01-07 05:34 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +                             "deprecated and please use 'text' instead")
and please use text
Don't need and

2025-01-07 05:34 UTC, farshidz commented on src/marqo/s2_inference/languagebind/video/modeling_video.py
> +def _expand_mask(mask: torch.Tensor, dtype: torch.dtype, tgt_len: Optional[int] = None):
Function repeated three times

2025-01-07 05:34 UTC, farshidz commented on src/marqo/s2_inference/languagebind/image/processing_image.py
> +    if isinstance(image_path, str):
What is this change addressing?

2025-01-07 05:34 UTC, farshidz commented on tests/core/inference/test_languagebind_model.py
> +    def test_loading_languagebind_model_from_a_hf_repo(self):
Test HF with auth

2025-01-07 05:34 UTC, farshidz commented on tests/core/inference/test_languagebind_model.py
> +        model_auth = ModelAuth(
Test S3 without auth as well

2025-01-07 05:34 UTC, farshidz commented on tests/core/inference/test_languagebind_model_properties.py
> +    def test_supported_modalities(self):
This shows up in test report (depending on the tool) so keep it concise and preferably one sentence e.g., "Test language modality is required and at least ..." 
Also I don't understand "and at least one of the other modalities must be supported."?

2025-01-07 09:05 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +    MODEL_NAME_CLIP_TYPE_MAPPING = {
These are registered models. I mean these variables can also be stored in the model properties.

2025-01-07 09:06 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +class CLIPType(MarqoBaseModel):
A term used by Languagebind, check [here](https://github.com/marqo-ai/marqo/blob/5b4f604303e9b54ea82704cc6db7275f532d70e8/src/marqo/s2_inference/languagebind/__init__.py#L34)

2025-01-07 09:08 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +            raise InvalidModelPropertiesError(
is any change required here?

2025-01-07 09:08 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                    f"If you are loading a custom model, please provide the modelLocation and remove the 'name' field "
done

2025-01-07 09:10 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                if modality == Modality.TEXT or modality == Modality.TEXT_2:
It's for `text`. Owen wants us to accept `text` in the supported modalities, but TEXT is already occupied by `language` so I use TEXT_2 here. Is there a good way to do this?

2025-01-07 09:10 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                if modality == Modality.TEXT or modality == Modality.TEXT_2:
I don't want to change TEXT: "language" to LANGUAGE: "language" in this PR as it's kind of risky.

2025-01-07 09:14 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                elif model_location.hf and not model_location.hf.filename:
If there is a file name, it will be processed by `self._download_languagebind_model`. This logic also applies for s3

2025-01-07 09:18 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +            raise InternalError("Invalid model properties provided. Either 'name' or 'modelLocation' must be provided.")
This should already be verified when instantiating the model_properties. Yeah I can change it to InvalidModelPropertiesError

2025-01-07 09:19 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        """Custom tokenizer loading. The tokenizer can be loaded in twa ways:
done

2025-01-07 09:21 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        elif tokenizer_location.hf and (not tokenizer_location.hf.filename):
Changed if logic to make it clearer

2025-01-07 09:31 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        if isinstance(content[0], str):
Yes, this is the assumption. All items in the list must be of the same type to do a batch inference.

2025-01-07 09:34 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        if isinstance(content[0], str):
As for the 0 issue, should we do that check in the s2_inference function?

2025-01-07 09:35 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        if isinstance(content[0], str):
Yeah these are really good points. I am just not sure if it should be in the scope of this PR.

2025-01-07 09:36 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +        """Validate that at least one location is provided."""
Yes, exactly one

2025-01-07 09:39 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +        auth_required = values.get("authRequired")
I have removed it from the model properties

2025-01-07 09:39 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +        auth_required = values.get("authRequired")
removed it from the model properties

2025-01-07 09:41 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model_properties.py
> +                             "deprecated and please use 'text' instead")
done

2025-01-07 09:42 UTC, wanliAlex commented on src/marqo/s2_inference/languagebind/image/processing_image.py
> +    if isinstance(image_path, str):
To ensure Languagebind model can take PIL Object as input directly so we don't have to write the image as a file.

2025-01-07 09:53 UTC, wanliAlex commented on tests/core/inference/test_languagebind_model_properties.py
> +    def test_supported_modalities(self):
Changed doc string

2025-01-07 10:00 UTC, wanliAlex commented on src/marqo/s2_inference/languagebind/video/modeling_video.py
> +def _expand_mask(mask: torch.Tensor, dtype: torch.dtype, tgt_len: Optional[int] = None):
done

2025-01-08 01:03 UTC, wanliAlex commented on tests/core/inference/test_languagebind_model.py
> +        model_auth = ModelAuth(
Make sure we have tests for URL.

2025-01-08 01:07 UTC, wanliAlex commented on tests/core/inference/test_languagebind_model.py
> +        model_auth = ModelAuth(
Mock it in this iteration.

2025-01-08 03:36 UTC, wanliAlex commented on tests/core/inference/test_languagebind_model.py
> +    def test_loading_languagebind_model_from_a_hf_repo(self):
Added tests for private HF and public s3 url

2025-01-08 03:36 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                if modality == Modality.TEXT or modality == Modality.TEXT_2:
We now map `text` to `language` and use `language` internally in Marqo.

2025-01-08 03:36 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +        if isinstance(content[0], str):
Added check

2025-01-08 13:26 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +class CLIPType(MarqoBaseModel):
Hmm but does it make sense? We don't have to copy their terminology

2025-01-09 03:35 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +            raise InternalError("Invalid model properties provided. Either 'name' or 'modelLocation' must be provided.")
If it's validated upstream, then you're right, should be internal here as it indicates a bug in the upstream validation process.

2025-01-09 03:49 UTC, farshidz requested changes

2025-01-09 03:49 UTC, farshidz commented on src/marqo/s2_inference/languagebind/audio/modeling_audio.py
> +def _expand_mask(mask: torch.Tensor, dtype: torch.dtype, tgt_len: Optional[int] = None):
Doesn't look like the right place. Move as discussed to a common module

2025-01-09 03:49 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                    raise InvalidModelPropertiesError(
Should be internal

2025-01-09 03:49 UTC, farshidz commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +            raise InvalidModelPropertiesError(f"Invalid tokenizer location provided for tokenizer: "
Should be 500

2025-01-09 04:04 UTC, wanliAlex commented on src/marqo/s2_inference/languagebind/audio/modeling_audio.py
> +def _expand_mask(mask: torch.Tensor, dtype: torch.dtype, tgt_len: Optional[int] = None):
done

2025-01-09 04:05 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +                    raise InvalidModelPropertiesError(
Done

2025-01-09 04:05 UTC, wanliAlex commented on src/marqo/core/inference/embedding_models/languagebind_model.py
> +            raise InvalidModelPropertiesError(f"Invalid tokenizer location provided for tokenizer: "
done

2025-01-09 06:58 UTC, farshidz approved these changes

2025-01-09 07:02 UTC, merged