Global score modifiers for Hybrid search - RRF
marqo-ai/marqo pull request #1082
Opened 2024-12-27 19:33 UTC by vicilliar

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
no score modifiers for the end of the search chain in hybrid RRF search

* **What is the new behavior (if this is a feature change)?**
global score modifiers which are applied to the RRF scores in the combined result lists
`scoreModifiersGlobal` property added to `hybridParameters`

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2025-01-08 17:56 UTC, vicilliar commented
Backwards compatibility tests: https://github.com/marqo-ai/marqo/actions/runs/12676257514

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        logIfVerbose(String.format("Rerank count global found: %d", rerankCountGlobal), verbose);
nit can we use Vespa trace logging? Not even sure it's better but wondering

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                        rrf(
Global reranking should be independent of the fusion method. Why are we building it into rrf?

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(
You could have an error in both. Better to capture all errors then raise in case both are erroring out

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup result_to_rerank = result.clone();
You could clone in a custom loop and trim at the same time, in one pass. i.e. don't clone what you don't need to begin with

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup result_to_rerank = result.clone();
Probably worth comparing the time. I'm assuming clone is linear time

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup reranked_result = applyGlobalScoreModifiers(result_to_rerank, verbose);
nit Is there a way to avoid passing `verbose` around?

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        for (Hit hit : hits) {
Can we be smarter here and avoid this loop if user didn't provide global score modifiers?

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                if (mult_modifier != null && add_modifier != null) {
What if one is null and and the other isn't? Is that an error due to invariant violation?

2025-01-09 04:55 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                    logIfVerbose(
Does this only happen for legacy indexes? What do we get for new ones if global score modifiers aren't provided?

2025-01-09 04:55 UTC, farshidz commented on vespa/src/test/java/ai/marqo/search/HybridSearcherTest.java
> +    @Nested
Is unit test coverage TODO?

2025-01-09 05:28 UTC, vicilliar commented on vespa/src/test/java/ai/marqo/search/HybridSearcherTest.java
> +    @Nested
yes it is, still figuring out how to add the matchfeatures parameters properly

2025-01-09 05:30 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                        rrf(
Fair point. I can bring this logic out into its own function

2025-01-09 05:30 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(
will do

2025-01-09 05:32 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        for (Hit hit : hits) {
Can we assume that if hit[0] does not have global score modifiers, we skip the process entirely?

2025-01-09 05:32 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                if (mult_modifier != null && add_modifier != null) {
Yes it should error out. A hit should either have both (2.15.0 onwards) or neither (legacy)

2025-01-09 05:33 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                    logIfVerbose(
We have no way to tell if a hit is from 2.15 or if it's older, aside from the presence of the modifiers int he matchfeatures

2025-01-09 05:48 UTC, farshidz requested changes

2025-01-09 05:48 UTC, farshidz commented on src/marqo/core/constants.py
> +MARQO_SCORE_MODIFIERS_GLOBAL_MINIMUM_VERSION = semver.VersionInfo.parse('2.15.0')
nit Why not `MARQO_GLOBAL_SCORE_MODIFIERS`?

2025-01-09 05:48 UTC, farshidz commented on src/marqo/core/index_management/index_management.py
> +            logger.debug(f'Creating index {str(request.name)} with schema:\n{schema}')
I've really missed this one. Thank you :D

2025-01-09 05:48 UTC, farshidz commented on src/marqo/core/models/marqo_query.py
> +            raise ValueError(f"'scoreModifiers' is only supported for hybrid search if 'rankingMethod' is 'RRF'. "
As commented elsewhere, why should this depend on fusion/ranking method?

2025-01-09 05:48 UTC, farshidz commented on src/marqo/core/models/marqo_query.py
> +        if values.get("score_modifiers") is not None and hybrid_parameters.rankingMethod != RankingMethod.RRF:
Do we need to error out if it's not hybrid?

2025-01-09 05:48 UTC, farshidz commented on src/marqo/core/models/marqo_query.py
>      def validate_searchable_attributes_and_score_modifiers(cls, values):
Can you unit test this?

2025-01-09 05:48 UTC, farshidz commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +        match-features inherits base_rank_profile {
Are you sure you need to repeat the inheritance here?

2025-01-09 05:48 UTC, farshidz commented on tests/core/structured_vespa_index/test_schemas/no_score_modifiers.sd
> +   expression: mult_modifier(mult_weights) * score + add_modifier(add_weights)
Could just be `score` like before?

2025-01-09 05:48 UTC, farshidz commented on src/marqo/tensor_search/models/api_models.py
> +                raise ValueError(f"'rerankCount' is currently only supported for 'HYBRID' search with the 'RRF' rankingMethod.")
Aren't we validating this somewhere else as well? Which one is supposed to catch it first?

2025-01-09 05:48 UTC, farshidz commented on src/marqo/tensor_search/models/api_models.py
> +        if rerank_count is None:
I'm not sure this is a good idea. I think what empty rerank count means should be decided by the reranker code. This sort of logic seems out of scope for pydantic especially validation code

2025-01-09 05:48 UTC, farshidz commented on tests/compatibility_tests/search/test_search.py
> +                        for index, dict_item in enumerate(result["hits"]):
What are these changes doing?

2025-01-09 05:48 UTC, farshidz commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +                            "add_to_score": [
Add multiply to cover full functionality

2025-01-09 05:48 UTC, farshidz commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +    def _compare_search_results(self, expected_result, actual_result):
Comparison logic seems insufficient. At the very least establish result sets are identical in IDs (same IDs, same order). If comparing scores, compare for all results

2025-01-09 05:48 UTC, farshidz commented on tests/tensor_search/integ_tests/test_hybrid_search.py
> +    def test_hybrid_search_score_modifiers_wrong_ranking_method_fails(self):
Also test used with lexical/tensor search

2025-01-09 05:48 UTC, farshidz commented on tests/tensor_search/integ_tests/test_search_combined.py
> -    def test_search_query_ExpectedErrorRaisedForInvalidSearchMethod(self):
Where did this go?

2025-01-09 07:27 UTC, vicilliar commented on src/marqo/core/index_management/index_management.py
> +            logger.debug(f'Creating index {str(request.name)} with schema:\n{schema}')
This was actually you that put this in XD when we did a pair coding session

2025-01-09 07:29 UTC, vicilliar commented on src/marqo/core/models/marqo_query.py
> +        if values.get("score_modifiers") is not None and hybrid_parameters.rankingMethod != RankingMethod.RRF:
No, because normal `score_modifiers` should work fine for normal tensor and lexical search. We're just adding it now for `hybrid` for `RRF` specifically

2025-01-09 07:30 UTC, vicilliar commented on src/marqo/core/models/marqo_query.py
> +            raise ValueError(f"'scoreModifiers' is only supported for hybrid search if 'rankingMethod' is 'RRF'. "
Because for other retrieval/ranking methods like `tensor/lexical` or `lexical/tensor`, the normal root level `score_modifiers` doesn't make sense and is ambiguous. Referring to this table to clear things up:
![image](https://github.com/user-attachments/assets/a4f5ebe2-51a0-4378-b09b-b0038666eb97)

2025-01-09 07:31 UTC, vicilliar commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +        match-features inherits base_rank_profile {
Yes, this is following vespa docu. When I don't repeat this inheritance, it overwrites the base rank profile matchfeatures

2025-01-09 07:32 UTC, vicilliar commented on src/marqo/tensor_search/models/api_models.py
> +                raise ValueError(f"'rerankCount' is currently only supported for 'HYBRID' search with the 'RRF' rankingMethod.")
I'm quite sure this is the only place we're validating rerank count. Could you link where else we're validating it?

2025-01-09 07:33 UTC, vicilliar commented on src/marqo/tensor_search/models/api_models.py
> +        if rerank_count is None:
I see, so we could instead pass `None` to the java searcher, and let it do the reassignment?

2025-01-09 07:35 UTC, vicilliar commented on tests/core/structured_vespa_index/test_schemas/no_score_modifiers.sd
> +   expression: mult_modifier(mult_weights) * score + add_modifier(add_weights)
This would still end up being score, since mult_modifier is hardcoded to 1 and add_modifier is hardcoded to 0 if there are no score modifiers

2025-01-09 07:36 UTC, vicilliar commented on tests/tensor_search/integ_tests/test_search_combined.py
> -    def test_search_query_ExpectedErrorRaisedForInvalidSearchMethod(self):
Good catch, I think I deleted it by accident

2025-01-09 11:53 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException("Query limit cannot be null.");
in what case would limit be null? is this a user error or marqo error?

2025-01-09 20:48 UTC, papa99do commented on src/marqo/core/models/marqo_query.py
> +            raise ValueError(f"'scoreModifiers' is only supported for hybrid search if 'rankingMethod' is 'RRF'. "
Thanks for clarifying this in a table. Is this documented somewhere?

2025-01-09 20:55 UTC, papa99do commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +            expression: add_modifier(query(marqo__add_weights_global))
I was considering doing a refactoring to move structured index schema to a jinja2 template as well. So that we can reuse these functions using macros. Not in the scope of this PR though.

2025-01-09 21:43 UTC, papa99do commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +        match-features: global_mult_modifier global_add_modifier
nit. since we need to use inheritance later, we could use the consistent format: 
```
match-features [inherits parent-profile]? {
    [feature]
    [feature]
}
```

2025-01-09 21:47 UTC, papa99do commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +            {%- for field in index.tensor_fields %} distance(field, {{ field.embeddings_field_name }}){% endfor -%}
nit. formatting suggestion, single we are using multi-line format here, instead of using `{%- -%}`, we can use `{% %}`

2025-01-09 21:47 UTC, papa99do commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +        match-features inherits base_rank_profile {
nit. formatting suggestion, single we are using multi-line format here, instead of using {%- -%}, we can use {% %}

2025-01-10 00:46 UTC, papa99do commented on src/marqo/tensor_search/models/api_models.py
> +        if rerank_count is None:
> what empty rerank count means should be decided by the reranker
@farshidz , do we have some difference use cases?

2025-01-10 00:49 UTC, papa99do commented on tests/compatibility_tests/search/test_search.py
> +                    tensor_fields=["new_field"]
nit. this field does not have to be a tensor field.

2025-01-10 00:50 UTC, papa99do commented on tests/compatibility_tests/search/test_search.py
> +            if index.get("type") is None or index.get("type") == 'unstructured':
should be `semi-structured`?

2025-01-10 00:51 UTC, papa99do commented on tests/compatibility_tests/search/test_search.py
> +                        for index, dict_item in enumerate(result["hits"]):
I think the `to_be_removed` doc solely serve the purpose of triggering the schema change. Would it be better if we delete it right away after inserting it? @vicilliar

2025-01-10 00:58 UTC, papa99do commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +        {"_id": "both1", "text_field": "dogs", "multiply_1": -1, "add_1": -1},  # HIGH tensor, LOW lexical
why is this LOW lexical? search term is `dogs` which matches the text field content

2025-01-10 01:02 UTC, papa99do commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +    def _compare_search_results(self, expected_result, actual_result):
I agree. Do we need to guarantee exact score match or a margin or just the order? Do we know whether the score could change? (such as when vespa is upgrade, etc.)

2025-01-10 01:28 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        logIfVerbose(String.format("Rerank count global found: %d", rerankCountGlobal), verbose);
I think we had a POC about using trace logging when introducing customer search in the first place. See https://github.com/marqo-ai/marqo/pull/890#issuecomment-2216604901 for detail.
We decided to delay the change since the change is not trivial, and we were in tight schedule. We can add an improvement ticket to check if this is a better option.

2025-01-10 02:15 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        logIfVerbose(String.format("Rerank count global found: %d", rerankCountGlobal), verbose);
I agree this is a good idea, but should be a separate ticket.

2025-01-10 02:20 UTC, vicilliar commented on src/marqo/core/constants.py
> +MARQO_SCORE_MODIFIERS_GLOBAL_MINIMUM_VERSION = semver.VersionInfo.parse('2.15.0')
updated

2025-01-10 02:23 UTC, vicilliar commented on src/marqo/core/models/marqo_query.py
> +            raise ValueError(f"'scoreModifiers' is only supported for hybrid search if 'rankingMethod' is 'RRF'. "
Thanks @papa99do ! This is not officially documented anywhere yet. Should we even be letting users in on this info? Since it leaks how we use vespa a bit. Maybe we want it to be abstracted. To answer your question, the normal `scoreModifiers` **is** global score modifiers, for RRF. Previously (2.14 and earlier), using the `scoreModifiers` parameter for RRF would error out. Now, it will be used as global.

2025-01-10 02:46 UTC, vicilliar commented on src/marqo/core/models/marqo_query.py
>      def validate_searchable_attributes_and_score_modifiers(cls, values):
done

2025-01-10 02:47 UTC, vicilliar commented on tests/compatibility_tests/search/test_search.py
> +                        for index, dict_item in enumerate(result["hits"]):
Yes @papa99do that's correct, it's just to confirm the semi-structured schema change doesn't break add docs/search. Deleting it right away is also fine, does it not revert the schema change?

2025-01-10 03:31 UTC, vicilliar commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +                            "add_to_score": [
done

2025-01-10 03:32 UTC, vicilliar commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +    def _compare_search_results(self, expected_result, actual_result):
good catch, i will loop through all results and compare IDs + scores. @adityabharadwaj198 is this the standard comparison behavior for all compatibility tests? I just copied one of the existing tests

2025-01-10 03:44 UTC, vicilliar commented on tests/tensor_search/integ_tests/test_hybrid_search.py
> +    def test_hybrid_search_score_modifiers_wrong_ranking_method_fails(self):
done

2025-01-10 03:56 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException("Query limit cannot be null.");
Interestingly, I can't replicate a case where limit is null. Vespa seems to autofill it to 10 if we don't pass anything. I just set this as a failsafe.

2025-01-10 03:57 UTC, vicilliar commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +            expression: add_modifier(query(marqo__add_weights_global))
I agree, is there a ticket for this?

2025-01-10 03:58 UTC, vicilliar commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +        match-features: global_mult_modifier global_add_modifier
What would the difference be, functionally? Also base_rank_profile should never inherit from a parent profile anyway since it's the base. I'd rather keep it one line if possible

2025-01-10 04:09 UTC, vicilliar commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +        {"_id": "both1", "text_field": "dogs", "multiply_1": -1, "add_1": -1},  # HIGH tensor, LOW lexical
ah right I forgot to remove this comment. There was supposed to be another doc with a higher lexical score but i removed it.

2025-01-10 04:18 UTC, vicilliar commented on tests/compatibility_tests/search/test_search.py
> +                    tensor_fields=["new_field"]
I see, having it as a tensor field wouldn't hurt though right?

2025-01-10 07:22 UTC, vicilliar commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +        match-features inherits base_rank_profile {
Kept the format using {%- but moved them to new lines, so the output looks something like this:
```
match-features inherits base_rank_profile {
            closest(marqo__embeddings_tensor_field)
            distance(field, marqo__embeddings_tensor_field)
        }
```

2025-01-10 07:25 UTC, vicilliar commented on tests/core/structured_vespa_index/test_schemas/no_score_modifiers.sd
> +   expression: mult_modifier(mult_weights) * score + add_modifier(add_weights)
Actually you're right, I'll change this to `score`

2025-01-10 17:07 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup result_to_rerank = result.clone();
Done, used one pass.

2025-01-10 17:18 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        for (Hit hit : hits) {
done. skipping entire score modifier process if the first hit doesn't have the right match features. If any other hits in the list are missing one or both of these (during the loop), we will now error out.

2025-01-10 17:19 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                    logIfVerbose(
If global score modifiers aren't provided for the first hit, we skip the whole process.

2025-01-12 23:03 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        logIfVerbose(String.format("Rerank count global found: %d", rerankCountGlobal), verbose);
Let's leave it for now. Trace logging seems like the logical way to do this in Vespa, but currently in Marqo there's no way to set Vespa trace level for a query.

2025-01-12 23:04 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        for (Hit hit : hits) {
Can't you look at the query? Using result match features of the first hit may not be a good idea

2025-01-12 23:06 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                if (mult_modifier != null && add_modifier != null) {
Then you should cover that and raise an internal/runtime error

2025-01-12 23:13 UTC, papa99do commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +            expression: add_modifier(query(marqo__add_weights_global))
created a ticket to track this: https://s2search.atlassian.net/browse/MOSD-308

2025-01-12 23:17 UTC, papa99do commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +            query["marqo__hybrid.rerankCountGlobal"] = marqo_query.rerank_count
nit. why do we use camelCase here? Is it the convention of `marqo__hybrid.` query params? seems not consistent.

2025-01-12 23:18 UTC, farshidz commented on src/marqo/core/models/marqo_query.py
> +            raise ValueError(f"'scoreModifiers' is only supported for hybrid search if 'rankingMethod' is 'RRF'. "
I don't think it's ambiguous at all. Global score modifiers are still global score modifiers (i.e. applied to results collected from all shards). Why shouldn't they work for other hybrid modes?

2025-01-12 23:22 UTC, farshidz commented on src/marqo/tensor_search/models/api_models.py
> +        if rerank_count is None:
@papa99do it's more about what one expects from a pydantic models and what belongs where in principle. Does that make sense?

2025-01-12 23:24 UTC, farshidz commented on src/marqo/core/semi_structured_vespa_index/semi_structured_vespa_schema_template.sd.jinja2
> +            expression: add_modifier(query(marqo__add_weights_global))
@papa99do I'm not sure if I'm personally a big fan of jinja templates. Let's discuss this

2025-01-12 23:44 UTC, papa99do commented on tests/compatibility_tests/search/test_search.py
> +                        for index, dict_item in enumerate(result["hits"]):
No, deleting a document won't cause schema change. Fields can be added to a schema but never removed (because we don't know if other documents have this fields or not)

2025-01-13 00:00 UTC, papa99do commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +    for i in range(len(expected_result.get("hits"))):
do we need to compare other fields in the `hits` list as well?

2025-01-13 00:06 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(tensorOrLexicalErrors);
We always throw RuntimeException, which will cause Vespa to return 500 error. Is this expected? Should we distinguish user error from transient server error? 500 server error usually indicates the request is retriable.

2025-01-13 00:07 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(tensorOrLexicalErrors);
@vicilliar , you mentioned you also fixed an issue we discussed before. Could you add a comment to highlight the fix? Thanks

2025-01-13 00:08 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup reranked_result = applyGlobalScoreModifiers(resultToRerank, verbose);
nit. naming convention. reranked_result -> rerankedResult

2025-01-13 00:18 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                    hit.setRelevance(modified_score);
should we keep the original score in a meta field? like what we do for _lexcial_score and _tensor_score?

2025-01-13 00:20 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                            "Failed to apply global score modifiers. Hit "
nit. using fail fast pattern can save us from too deeply nested code structure.

2025-01-13 04:12 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                        rrf(
I'll leave this open to discuss why we're limited to rrf still

2025-01-13 06:13 UTC, farshidz requested changes

2025-01-13 06:13 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(tensorOrLexicalErrors);
This is a fair point. We could get more specific perhaps

2025-01-13 06:13 UTC, farshidz commented on tests/compatibility_tests/search/test_search.py
> +                        for index, dict_item in enumerate(result["hits"]):
Yes let's delete right away to be explicit, plus a comment as to what we're trying to do by adding that doc

2025-01-13 06:13 UTC, farshidz commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +    for i in range(len(expected_result.get("hits"))):
Could we just say result sets have to be exactly identical?

2025-01-13 06:13 UTC, farshidz commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +            expected_result.get("hits")[i]["_id"],
I'd compare ID first. No point in failing on score mismatch if the IDs are different (it's misleading, score isn't the problem if IDs are different)

2025-01-13 06:13 UTC, farshidz commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                mult_modifier = hitMatchFeatures.getDouble("global_mult_modifier");
We shouldn't run all this code even when the request isn't using global score modifiers

2025-01-13 06:13 UTC, farshidz commented on src/marqo/core/models/marqo_query.py
> +            raise ValueError(f"'scoreModifiers' is only supported for hybrid search if 'rankingMethod' is 'RRF'. "
Agreed to make this a follow-up PR

2025-01-13 08:05 UTC, vicilliar commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +            expected_result.get("hits")[i]["_id"],
making the change so we compare entire result lists

2025-01-13 08:07 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                    hit.setRelevance(modified_score);
I don't see much point. We aren't doing this for normal tensor or lexical searches either. Any thoughts @farshidz ?

2025-01-13 11:36 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        for (Hit hit : hits) {
done, looking at `marqo__mult_weights_global` and `marqo__add_weights_global` in query instead

2025-01-13 11:38 UTC, vicilliar commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +            query["marqo__hybrid.rerankCountGlobal"] = marqo_query.rerank_count
We use `marqo__` at the start of all unique input params, just so it never collides with a new one vespa might introduce. I just used camelCase to follow java conventions. `marqo__hybrid.rrf_k` uses an underscore because `marqo__hybrid.rrfK` seemed like an odd choice.

2025-01-13 11:40 UTC, vicilliar commented on tests/compatibility_tests/search/test_search_with_score_modifiers.py
> +    for i in range(len(expected_result.get("hits"))):
done

2025-01-13 11:41 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup reranked_result = applyGlobalScoreModifiers(resultToRerank, verbose);
updated. no longer using `reranked_result`

2025-01-13 11:54 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                            "Failed to apply global score modifiers. Hit "
Answered this in another comment. We fully skip the score modifiers step if `marqo__mult_weights_global` and `marqo__add_weights_global` are not set or empty. This extra check is just to fail with a good error if one of the hits is missing a required field for global score modifiers

2025-01-13 11:55 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                mult_modifier = hitMatchFeatures.getDouble("global_mult_modifier");
done

2025-01-13 13:04 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(tensorOrLexicalErrors);
I agree we should have a more sophisticated system to handle the error codes thrown here, but as a different feature.

2025-01-13 13:09 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(tensorOrLexicalErrors);
@farshidz Do we have a ticket for the hybrid searcher swallowing errors? I remember one being made but I can't find it on the board

2025-01-13 13:11 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +            throw new RuntimeException(tensorOrLexicalErrors);
Nvm found it: https://s2search.atlassian.net/jira/polaris/projects/MOSD/ideas/view/4863474?selectedIssue=MOSD-225&issueViewLayout=sidebar&issueViewSection=overview&atlOrigin=eyJpIjoiNDdiNzlkMzE4MzUyNGFmZjhkYmM1NDI0NTNjZTNiMjIiLCJwIjoiaiJ9

2025-01-14 04:54 UTC, papa99do commented on tests/tensor_search/test_pagination.py
> +                            #                     paginated_search_results["hits"][i]["_score"])
why did we stop verifying non-rrf cases?

2025-01-14 05:22 UTC, farshidz commented on src/marqo/tensor_search/models/api_models.py
> +        if rerank_count is None:
Also missing rerankCount should rerank all results not limit+offset

2025-01-14 05:59 UTC, papa99do commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +            query["marqo__hybrid.rerankCountGlobal"] = marqo_query.rerank_count
actually it is used in `hybrid_parameters` :D , but it's all right, it's internal so I guess we can always change it in the future.

2025-01-14 06:08 UTC, papa99do commented on src/marqo/tensor_search/models/api_models.py
> +                raise ValueError(f"'rerankCount' is currently only supported for 'HYBRID' search with the 'RRF' rankingMethod.")
So just to verify, the rerank count only applies to the RRF, but not other hybrid search types. But global score modifier applies to all types, why?

2025-01-14 06:10 UTC, farshidz approved these changes, later dismissed

2025-01-14 06:41 UTC, vicilliar commented on tests/tensor_search/test_pagination.py
> +                            #                     paginated_search_results["hits"][i]["_score"])
The add documents call used to be faulty and only add 100 docs instead of 400, then we paginated with page sizes 100 and 200. Essentially this means the `test_pagination_hybrid` test didn't actually test pagination at all.

When I updated the add docs call to properly add the 400 documents, this score test started failing, meaning the feature actually has been broken for a while. This aligns with our existing ticket to fix it: https://s2search.atlassian.net/jira/polaris/projects/MOSD/ideas/view/4863474?selectedIssue=MOSD-85&issueViewLayout=sidebar&issueViewSection=overview&atlOrigin=eyJpIjoiYzc0NDNkOTRlMjNhNDExNGE5YTdjYWJjOTZhY2YzYzIiLCJwIjoiaiJ9

I commented out the score checks for now so the pipeline passes.

2025-01-14 07:14 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup hitsForPostProcessing;
I cannot leave a comment for unchanged lines, but @farshidz mentioned that 
> default behavior if no rerankCount provided is to rerank everything we have

So I think  this logic should be removed?
```
if (rerankCountGlobal == null) {
            rerankCountGlobal = limit;
    ```

2025-01-14 07:21 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        // Post-process result list
Extract the logic to a method. It's easier to reason about a shorter method. We should try to avoid large method or class in general.

2025-01-14 07:35 UTC, papa99do commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                hitsForPostProcessing = result.hits();
Are we supporting non-rrf in customer search but hiding it from Marqo?

2025-01-14 08:54 UTC, vicilliar commented on src/marqo/tensor_search/models/api_models.py
> +                raise ValueError(f"'rerankCount' is currently only supported for 'HYBRID' search with the 'RRF' rankingMethod.")
global score modifiers is also only allowed for RRF at the moment. It's validated in marqo_query here: https://github.com/marqo-ai/marqo/pull/1082/files#diff-c3c8cecf08fbb16bb29cf37a814b53e68278de883f58847ee77d89a47d68277cR70

2025-01-14 08:54 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup hitsForPostProcessing;
This was removed

2025-01-14 08:55 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +                hitsForPostProcessing = result.hits();
Yes. Because we want to implement this right away in the next release. We're disallowing it for other methods now to reduce the scope of testing

2025-01-14 09:06 UTC, vicilliar commented on vespa/src/main/java/ai/marqo/search/HybridSearcher.java
> +        HitGroup hitsForPostProcessing;
this was removed

2025-01-14 10:16 UTC, papa99do approved these changes
LGTM

2025-01-14 11:13 UTC, vicilliar commented on src/marqo/tensor_search/models/api_models.py
> +        if rerank_count is None:
done

2025-01-14 13:03 UTC, merged