add query strings to text
marqo-ai/marqo pull request #243
Opened 2022-12-18 07:36 UTC by tomhamer

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix for https://github.com/marqo-ai/marqo/issues/227

* **What is the current behavior?** (You can also link to an open issue here)
When lexical search is used, search queries are treated as match queries. If the user specifies an exact match with a query like 'two "dog"' (which would require only docs with the exact phrase "dog" in it), the user still gets results with the other token "two" included. 

* **What is the new behavior (if this is a feature change)?**
Now we move it to use query_string. This means that users are able to specify double quotes to enable an exact match.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
Yes (there were some errors though I believe with the pipeline itself though - will follow up with the team).

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [Not yet] Docs have been added / updated (for bug fixes / features)
   - will append the required docs changes to this PR, posting here though for first pass.

2022-12-19 05:10 UTC, pandu-k requested changes
Thanks for this - quite a simple solution!

Can a few tests be added? Especially around possible DSL usage - think if there can be any exploits.

2023-01-05 07:29 UTC, vicilliar commented
> 

Unit tests added to ensure query string functionality works properly. Other unit tests all passed. Haven't been able to observe any exploits yet.

2023-01-06 05:49 UTC, pandu-k approved these changes

2023-01-06 06:09 UTC, pandu-k reviewed
Waiting on testing for urls and email addresses

2023-01-06 06:37 UTC, vicilliar commented
Notes on this solution (could be further improved):

1. Double quotes don't necessarily force a search term to be in the results. For example: 'two "dog"' will still return some results with "two" and some with "dog", following query string logic.
2. Query strings throw errors for invalid syntax. We may want to use simple query strings instead, which is less strict (ignores syntax errors)

2023-01-09 05:25 UTC, pandu-k requested changes
Waiting for fix with URLs and email addresses

2023-01-17 09:31 UTC, vicilliar commented
Ready for merge.
Other enhancements turned into a new issue here: https://github.com/marqo-ai/marqo/issues/274
Documentation added. Commit here: https://github.com/marqo-ai/marqodocs/commit/0eccbd453dfab97a1ee43481a574daec1eb7a4b0

2023-01-17 09:40 UTC, pandu-k approved these changes

2023-01-17 09:41 UTC, merged