[Onnx clip draft] Adding the clip_onnx to our avaible models for faster inference
marqo-ai/marqo pull request #245
Opened 2022-12-20 08:30 UTC by wanliAlex

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
features

* **What is the current behavior?** (You can also link to an open issue here)
no onnx model for clip

* **What is the new behavior (if this is a feature change)?**
we have onnx model for clip model

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
not yet

* **Related Python client changes** (link commit/PR here)
no

* **Related documentation changes** (link commit/PR here)
not yet 

* **Other information**:
the model passes the performance test on a 50k image dataset
the detailed performance can be checked at [link](https://github.com/wanliAlex/fast-clip-research)

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2022-12-20 22:47 UTC, pandu-k requested changes
The main piece of feedback is that onnx_clip_utils seems to be an outdated copy of clip_utils. Can you make ONNX_CLIP a subclass of CLIP? Having two copies of the same code isn't very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) - unless you want to decouple the APIs for these two types of models.

We can already see issues with copying the code: clip_utils has already had an update with better error message, which hasn't propagated to your code: https://github.com/marqo-ai/marqo/blob/mainline/src/marqo/s2_inference/clip_utils.py#L62

2022-12-20 22:47 UTC, pandu-k commented on src/marqo/s2_inference/onnx_clip_utils.py
> +    '''
Typo? Should it be `_HF_MODEL_DOWNLOAD `?

2022-12-29 02:30 UTC, pandu-k commented
Thanks for your work on this PR @wanliAlex !

Just have a question:

Has this feature (not just the models in isolation) been tested at scale? We need to ensure that indexing and retrieval works as expected as part of the Marqo application.

2022-12-29 02:32 UTC, wanliAlex commented
> 

Yes, the end to end __indexing__ and __searching__ are tested on a 50k image dataset.

2022-12-29 02:36 UTC, pandu-k approved these changes
Thanks for this PR @wanliAlex !

2022-12-29 06:50 UTC, merged