Removing deprecated update_docs
marqo-ai/marqo pull request #517
Opened 2023-06-27 01:18 UTC by pandu-k

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-06-27 10:13 UTC, pandu-k commented
Tests passing:
- arm64 API tests: https://github.com/marqo-ai/marqo/actions/runs/5385753028
- unit tests: https://github.com/marqo-ai/marqo/actions/runs/5385751889

2023-06-28 08:00 UTC, vicilliar requested changes
Another note: You also may want to edit the tests in `test_add_documents_use_existing_tensors.py`, as they have `update_mode` set to `replace` as well

Do we have a py-marqo client change to go with this PR?

2023-06-28 08:00 UTC, vicilliar commented on tests/tensor_search/test_add_documents.py
> -                   docs=bad_doc_arg, auto_refresh=True, update_mode='update', device="cpu"
Why was `update_mode='update'` here before? Maybe for previous tests that had that as the update mode, they could have the `use_existing_tensors` flag turned on

2023-06-28 08:00 UTC, vicilliar commented on tests/tensor_search/test_add_documents.py
>              add_res = tensor_search.add_documents(
We could consider removing these tests since the one below testing `replace` covers it

2023-06-28 08:00 UTC, vicilliar commented on tests/tensor_search/test_add_documents.py
>              add_res = tensor_search.add_documents(
could be a redundant test as well

2023-06-28 13:04 UTC, pandu-k commented
- unit tests: https://github.com/marqo-ai/marqo/actions/runs/5401423357
- CUDA DIND tests: https://github.com/marqo-ai/marqo/actions/runs/5401424359

2023-06-28 13:06 UTC, pandu-k commented
- unit tests: https://github.com/marqo-ai/marqo/actions/runs/5401445292
- cuda API tests: https://github.com/marqo-ai/marqo/actions/runs/5401446726

2023-06-28 13:07 UTC, pandu-k commented
> Another note: You also may want to edit the tests in `test_add_documents_use_existing_tensors.py`, as they have `update_mode` set to `replace` as well

Updated these too, and removed other remaining references I found to `update_mode`

2023-06-29 04:33 UTC, vicilliar approved these changes

2023-06-29 04:35 UTC, merged