Add 'bulk' to INDEX_NAMES_TO_IGNORE
marqo-ai/marqo pull request #598
Opened 2023-09-08 08:56 UTC by pandu-k

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-09-11 00:49 UTC, wanliAlex approved these changes, later dismissed

2023-09-11 05:13 UTC, wanliAlex submitted a review, later dismissed

2023-09-18 10:06 UTC, vicilliar requested changes

2023-09-18 10:06 UTC, vicilliar commented on tests/tensor_search/test_create_index.py
> +        assert {'index_name': 'some-bulk'} in tensor_search.get_indexes(config=self.config)['results']
We should `assert {'index_name': 'bulkabc'} in tensor_search.get_indexes(config=self.config)['results']` as well here, for completeness.

2023-09-19 03:38 UTC, vicilliar approved these changes

2023-09-19 11:57 UTC, merged