Danyil/feature/use marqo commons
marqo-ai/marqo pull request #607
Opened 2023-09-25 08:32 UTC by danyilq

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-09-25 09:53 UTC, vicilliar requested changes

2023-09-25 09:53 UTC, vicilliar commented on src/marqo/s2_inference/model_registry.py
> +    all_properties['models'] = get_model_properties_dict()
Interesting solution, to import the marqo commons registry into the marqo registry and keep the rest of the code mostly the same! The next steps would be:

1. Remove all model properties references from here and only return the loaders. Change function name to `get_model_loaders` and file name to `model_loaders.py`
2. Update all references to `load_model_properties` in the repo and replace them with references to marqo commons.

@pandu-k could I get feedback on this approach? Is it worth doing, or would it be better to keep things as is?

2023-09-28 07:44 UTC, vicilliar requested changes

2023-09-28 07:44 UTC, vicilliar commented on src/marqo/s2_inference/model_loaders.py
> +def load_model_properties() -> Dict:
We should change the function name to `get_model_loaders()`. There are no more "properties" coming from this file anymore.

2023-09-28 07:44 UTC, vicilliar commented on src/marqo/s2_inference/model_loaders.py
> +    all_properties = dict()
let's update this variable to `loaders`

2023-09-28 07:44 UTC, vicilliar commented on src/marqo/s2_inference/onnx_clip_utils.py
> +        from marqo.s2_inference.s2_inference import get_model_properties_from_registry
Why is this not declared at the top of the file?

2023-09-28 07:44 UTC, vicilliar commented on src/marqo/s2_inference/s2_inference.py
> +from marqo.s2_inference.model_loaders import load_model_properties
change to get_model_loaders

2023-09-28 07:44 UTC, vicilliar commented on src/marqo/s2_inference/s2_inference.py
> +MODEL_LOADERS = load_model_properties()
change to get_model_loaders

2023-09-28 07:44 UTC, vicilliar commented on src/marqo/tensor_search/on_start_script.py
> +                        # ModelsForCacheing(),
Why was this commented out?

2023-09-28 07:44 UTC, vicilliar commented on src/marqo/tensor_search/tensor_search.py
> +    except InvalidSettingsArgError as e:
We should make the code here clarify that `InvalidSettingsArgError` is from `marqo_commons` and `InvalidArgError` is from `marqo`. Or else this line seems redundant. 

We could either add a comment explaining this or import it like `from marqo_commons.shared_utils.errors import InvalidSettingsArgError as CommonsInvalidSettingsArgError`

2023-09-28 07:44 UTC, vicilliar commented on tests/s2_inference/test_clip_onnx_utils.py
> +import marqo.s2_inference.model_loaders as model_registry
this is confusing. it's better to `import marqo.s2_inference.model_loaders as model_loaders`

2023-09-28 07:44 UTC, vicilliar commented on tests/tensor_search/test_create_index.py
> +        with patch.dict(os.environ, {EnvVars.MARQO_MAX_NUMBER_OF_REPLICAS: str(maximum_number_of_replicas)}):
this pattern looks good!

2023-09-28 07:44 UTC, vicilliar commented on tests/tensor_search/test_create_index.py
> +        with patch.dict(os.environ, {EnvVars.MARQO_MAX_NUMBER_OF_REPLICAS: str(maximum_number_of_replicas)}):
We should also make another test changing `EnvVars.MARQO_EF_CONSTRUCTION_MAX_VALUE`. Then another one changing both.

2023-09-28 07:44 UTC, vicilliar commented on tests/tensor_search/test_validation.py
> +            assert settings == validate_index_settings(settings,
Let's move all tests that directly test `validate_index_settings` from marqo commons into the marqo commons repo. That way they are coupled together and there is no need to import any commons errors into marqo test files.

2023-09-28 08:07 UTC, danyilq commented on src/marqo/s2_inference/onnx_clip_utils.py
> +        from marqo.s2_inference.s2_inference import get_model_properties_from_registry
due to a circular import issue, we'd have to resolve it. maybe onnx clip object can work without that function but it needs deeper investigation

2023-09-28 08:08 UTC, danyilq commented on src/marqo/tensor_search/on_start_script.py
> +                        # ModelsForCacheing(),
whoops, it wasn't supposed to be part of pr.

2023-09-28 09:27 UTC, vicilliar requested changes

2023-09-28 09:27 UTC, vicilliar commented on src/marqo/s2_inference/model_loaders.py
> +def _get_model_load_mappings() -> Dict:
Just realized we don't need 2 separate functions anymore. Won't this have the same output:
```
def get_model_loaders() -> Dict:
      return {'clip':CLIP,
            'open_clip': OPEN_CLIP,
            'sbert':SBERT,
            'test':TEST,
            'sbert_onnx':SBERT_ONNX,
            'clip_onnx': CLIP_ONNX,
            "multilingual_clip" : MULTILINGUAL_CLIP,
            "fp16_clip": FP16_CLIP,
            'random':Random,
            'hf':HF_MODEL}
```

2023-09-28 09:27 UTC, vicilliar commented on tests/tensor_search/test_create_index.py
> +        with patch.dict(os.environ, {EnvVars.MARQO_MAX_NUMBER_OF_REPLICAS: str(maximum_number_of_replicas)}):
was this addressed?

2023-10-03 17:48 UTC, vicilliar commented on src/marqo/s2_inference/onnx_clip_utils.py
> +        from marqo.s2_inference.s2_inference import get_model_properties_from_registry
@pandu-k Do you have any input on resolving this circular import? Declaring it in this init function works but it feels a bit hacky. The issue is that `onnx_clip_utils` here calls `s2_inference`, which imports from `model_loaders`, which imports from `onnx_clip_utils`.

2023-10-04 23:20 UTC, pandu-k commented on src/marqo/s2_inference/onnx_clip_utils.py
> +        from marqo.s2_inference.s2_inference import get_model_properties_from_registry
This strange situation is an indication that our package structure isn't ideal. Good pick up @vicilliar! 

I think the best way is for the model_registry is purely for static data (a.k.a the model properties). 

We can then create a new file that has `_get_model_load_mappings()` and `load_model_properties()`. Would that solve this?

2024-06-24 00:03 UTC, closed without merging