Change unstructured index numeric type to long double
marqo-ai/marqo pull request #722
Opened 2024-01-18 01:31 UTC by wanliAlex

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Change unstructured index numeric type to long double

* **What is the current behavior?** (You can also link to an open issue here)
we use float and double 

* **What is the new behavior (if this is a feature change)?**
Change unstructured index numeric type to long double

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
no

* **Related Python client changes** (link commit/PR here)
no

* **Related documentation changes** (link commit/PR here)
no

* **Other information**:
no

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

2024-01-31 00:29 UTC, farshidz requested changes
* Add input validation so out of range values don't cause 500. Input validation must take index version into account for unstructured (i.e. older indexes don't support double/long so lower limits)
* Ensure values at limit boundaries are tested, and also test past boudaries we get 400

2024-01-31 00:29 UTC, farshidz commented on tests/tensor_search/integ_tests/test_add_documents_structured.py
> +            ({"double_field_1": 1e10 + 0.123249357987123}, False),  # large positive float
Are these the min/max acceptable values?

2024-01-31 23:02 UTC, wanliAlex commented
> * Add input validation so out of range values don't cause 500. Input validation must take index version into account for unstructured (i.e. older indexes don't support double/long so lower limits)
> * Ensure values at limit boundaries are tested, and also test past boudaries we get 400

I will add test cases at the boundaries.

As for the index version, I will leave it to manual, integration tests.

2024-02-05 23:00 UTC, farshidz commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +                                        f'If you wish to store a value outside of this range, creating a field with type '
"create a field with type"

2024-02-05 23:00 UTC, farshidz commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +        MAX_FLOAT = 3.4028235e38
Best to define these at class level similar to `_VESPA_DOC_ID` so that they're stored only once not per function call, and also for clarity

2024-02-05 23:00 UTC, farshidz commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +        if (value > MAX_FLOAT) or (0 < value < SMALLEST_POS_FLOAT) or (value < MIN_FLOAT) or \
What happens if `< SMALLEST_POS_FLOAT` or `> LARGEST_NEG_FLOAT`? If truncation/rounding, I think that is acceptable and we shouldn't error out for that

2024-02-05 23:00 UTC, farshidz commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +            raise InvalidDataRangeError(f"Invalid value {value} for long field. Expected a value in the range "
Does this actually work? If Vespa long range smaller than Python's?

2024-02-05 23:00 UTC, farshidz commented on tests/tensor_search/test_api.py
> +        self.assertEqual(response.json()["errors"], True)
Why remove the message validation?

2024-02-05 23:09 UTC, farshidz commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +            if isinstance(marqo_value, (int, float)) and not index_field.type == FieldType.Bool:
Shouldn't need not index_field.type == FieldType.Bool because boolean conversion to int is done further down in line 73

2024-02-06 01:03 UTC, wanliAlex commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +                                        f'If you wish to store a value outside of this range, creating a field with type '
done

2024-02-06 01:03 UTC, wanliAlex commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +            raise InvalidDataRangeError(f"Invalid value {value} for long field. Expected a value in the range "
Yes, Vespa will error out for ` int("1" * 30)`. We have a test case for this.

2024-02-06 01:03 UTC, wanliAlex commented on tests/tensor_search/test_api.py
> +        self.assertEqual(response.json()["errors"], True)
Add back a different message validation

2024-02-06 01:03 UTC, wanliAlex commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +        MAX_FLOAT = 3.4028235e38
Make sense. Done

2024-02-06 01:03 UTC, wanliAlex commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +            if isinstance(marqo_value, (int, float)) and not index_field.type == FieldType.Bool:
We need to exclude the `boolean` type here. I will use `if type(marqo_value) in (float, int)` to check instead of `isinstance`

2024-02-06 01:03 UTC, wanliAlex commented on src/marqo/core/structured_vespa_index/structured_vespa_index.py
> +        if (value > MAX_FLOAT) or (0 < value < SMALLEST_POS_FLOAT) or (value < MIN_FLOAT) or \
They will be round to 0. We think this is a reasonable behavior and we skip the check for that.

2024-02-06 03:48 UTC, farshidz approved these changes

2024-02-06 03:49 UTC, merged