fix get_settings tests
marqo-ai/marqo pull request #754
Opened 2024-02-02 09:02 UTC by vicilliar

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
tests fix

* **What is the current behavior?** (You can also link to an open issue here)
skipped tests

* **What is the new behavior (if this is a feature change)?**
- `get_settings` tests are fixed and moved under `test_index_management`
- `get_document` tests are fixed and moved under `tensor_search/integ_tests`
- `get_documents_by_ids` tests are fixed and moved under `tensor_search/integ_tests`
- `test_api.py` tests improved (index tests created on startup instead of per test)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
yes

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2024-02-21 14:00 UTC, farshidz requested changes

2024-02-21 14:00 UTC, farshidz commented on tests/core/index_management/test_get_settings.py
> +            retrieved_settings = IndexSettings.from_marqo_index(self.unstructured_default_index).dict(exclude_none=True, by_alias=True)
Are we testing `from_marqo_index`? in that case this isn't testing index management really so doesn't belong here. Did you mean to call `index_management.get_index`?

2024-02-22 04:20 UTC, vicilliar commented on tests/core/index_management/test_get_settings.py
> +            retrieved_settings = IndexSettings.from_marqo_index(self.unstructured_default_index).dict(exclude_none=True, by_alias=True)
Hey Farshid, what do you recommend? I'm just trying to test the way users will access `get_settings`, which I found from the API file here: https://github.com/marqo-ai/marqo/blob/48b0ac297270697d98f1d29818485244d2465091/src/marqo/tensor_search/api.py#L284

2024-03-06 23:28 UTC, farshidz approved these changes

2024-03-06 23:29 UTC, merged