Improve interpolation edge case management
marqo-ai/marqo pull request #825
Opened 2024-04-30 08:53 UTC by farshidz

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* Improve edge case handling for vector interpolation
* Address SLERP calculation bug

* **What is the current behavior?** (You can also link to an open issue here)
NA

* **What is the new behavior (if this is a feature change)?**
NA

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
Yes

* **Related Python client changes** (link commit/PR here)
No

* **Related documentation changes** (link commit/PR here)
No

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2024-05-01 04:59 UTC, vicilliar submitted a review, later dismissed

2024-05-01 06:43 UTC, wanliAlex requested changes

2024-05-01 06:43 UTC, wanliAlex commented on src/marqo/core/search/recommender.py
>          if isinstance(documents, dict):
Do you think you can put this logic in line 70 to avoid duplication?

2024-05-01 06:43 UTC, wanliAlex commented on src/marqo/core/utils/vector_interpolation.py
Raises are missing

2024-05-02 00:45 UTC, wanliAlex approved these changes

2024-05-02 01:30 UTC, merged