Patch index creation and deletion resilience
marqo-ai/marqo pull request #866
Opened 2024-06-17 02:41 UTC by wanliAlex

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Creating and deleting indexes are non-atomic processes in Marqo consisting of two steps:
- Update the Vespa application package
- Update Marqo index metadata in Vespa
A failure may put Marqo into an intermediate state where the target index can neither be deleted nor be created.

* **What is the new behavior (if this is a feature change)?**
We don’t intend to add transaction management here, but in case of a failure, the user should be able to bring Marqo to a consistent state by repeating the call and getting a 200 response. 

Tests are added to ensure Marqo can behave as mentioned above.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
running

* **Related Python client changes** (link commit/PR here)
no
* **Related documentation changes** (link commit/PR here)
no

* **Other information**:
no

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2024-06-20 06:38 UTC, farshidz requested changes
* Simplify the tests, only test failure between stages that persist a change
* Test create index when bootstrapping hasn't been done, or has been done partially

2024-06-20 06:38 UTC, farshidz commented on src/marqo/core/index_management/index_management.py
> +            return None
Return None is redundant here

2024-06-20 06:38 UTC, farshidz commented on tests/tensor_search/integ_tests/test_create_index_resilience.py
> +    Users should at least be able to bring Marqo to a consistent state by repeating the call to create index and get a
Create and also delete

2024-06-20 06:38 UTC, farshidz commented on tests/tensor_search/integ_tests/test_create_index_resilience.py
> +        cls.index_management.bootstrap_vespa()
You don't really need this, but it's okay to have it too

2024-06-20 06:38 UTC, farshidz commented on tests/tensor_search/integ_tests/test_create_index_resilience.py
> +        self.index_name = "test_index_creation_resilience"
Use `self.random_index_name()` instead to ensure no name clash

2024-06-20 06:38 UTC, farshidz commented on tests/tensor_search/integ_tests/test_create_index_resilience.py
> +            tensor_search.delete_index(self.config, self.index_name)
Call IndexManagement class

2024-06-20 06:38 UTC, farshidz commented on tests/tensor_search/integ_tests/test_create_index_resilience.py
> +            tensor_search.delete_index(self.config, self.index_name)
No need for this if using a random name

2024-06-20 06:38 UTC, farshidz commented on tests/tensor_search/integ_tests/test_create_index_resilience.py
> +            with self.assertRaises(Exception) as e:
You could use a custom exception class and you won't need to verify the message, or even have a message

2024-06-21 03:26 UTC, wanliAlex commented on src/marqo/core/index_management/index_management.py
> +            return None
Done

2024-06-24 00:36 UTC, farshidz approved these changes

2024-06-24 00:36 UTC, merged