add model_size to languagebind
marqo-ai/marqo pull request #962
Opened 2024-09-11 09:58 UTC by RaynorChavez

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)

* **Related Python client changes** (link commit/PR here)

* **Related documentation changes** (link commit/PR here)

* **Other information**:

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2024-09-11 22:14 UTC, wanliAlex requested changes

2024-09-11 22:14 UTC, wanliAlex commented on .github/workflows/unit_test_200gb_CI.yml
> +          export MARQO_MAX_CPU_MODEL_MEMORY=15
Let's not change this one because we want the CPU unit test to be light weight. Can you move your full model test to large model test?

2024-09-11 22:14 UTC, wanliAlex commented on tests/s2_inference/test_automatic_model_ejection_and_concurrency.py
> +    @pytest.mark.skip(reason="skipping since we have increased max model size to 15 GB")
Once you move the full model test to large model test, let's not skip this

2024-09-11 22:14 UTC, wanliAlex commented on tests/test_documentation.py
> +@pytest.mark.skip(reason="skipping since we have a CI pipeline for this")
delete the test if you believe this is not necessary

2024-09-11 23:33 UTC, farshidz approved these changes
Looks good after Li's requested changes

2024-09-12 00:20 UTC, wanliAlex approved these changes

2024-09-12 00:22 UTC, merged